# Generated by Django 2.1.3 on 2019-01-01 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('flag', models.IntegerField()),
                ('record_date', models.CharField(max_length=100)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 0, 9, 52, 35242, tzinfo=utc))),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
